// SPDX-License-Identifier: AGPL-3.0-only
// Generated by generate.py; production source SHA256: bad2afc59183a4b46fd094864ef88ae428517a23dee0d00f1d9e87de7503b33b
template<bool PQ_VEC_SCALES>
__device__ __forceinline__ void atlas_dev_moe_m128_impl(
    const unsigned char* __restrict__ A_packed,
    const unsigned char* __restrict__ A_scale,
    const unsigned long long* __restrict__ B_packed_ptrs,
    const unsigned long long* __restrict__ B_scale_ptrs,
    const float* __restrict__ scale2_vals,
    __nv_bfloat16* __restrict__ C,
    const int* __restrict__ expert_offsets,
    const int* __restrict__ sorted_token_ids,
    unsigned int num_experts,
    unsigned int N,
    unsigned int K,
    unsigned int work_expert_id,
    unsigned int work_m_tile,
    unsigned int work_n_tile
) {
    static_assert(PQ_VEC_SCALES, "vector scales only");
    constexpr unsigned DEV_M_TILE = 128;
    const unsigned int expert_id = work_expert_id;
    if (expert_id >= num_experts) return;

    const int m_start = expert_offsets[expert_id];
    const int m_end = expert_offsets[expert_id + 1];
    const int M_expert = m_end - m_start;
    if (M_expert <= 0) return;

    const int cta_m_local = work_m_tile * DEV_M_TILE;
    if (cta_m_local >= M_expert) return;

    const unsigned int cta_m = m_start + cta_m_local;
    const unsigned int cta_n = work_n_tile * N_TILE_LG;
    const unsigned char* B_expert =
        (const unsigned char*)B_packed_ptrs[expert_id];
    const unsigned char* S_expert =
        (const unsigned char*)B_scale_ptrs[expert_id];
    const float scale2 = scale2_vals[expert_id];
    if (B_expert == 0) return;

    const unsigned int warp_id = threadIdx.x / 32;
    const unsigned int lane_id = threadIdx.x % 32;
    const unsigned int warp_m_offset = warp_id * 16;
    const unsigned int group_id = lane_id >> 2;
    const unsigned int tid = lane_id & 3;

    // A is already compact FP4. Keep each row 16-byte aligned because the
    // loader issues 16-byte cp.async operations for both halves of the row.
    // (A 36-byte stride faults as CUDA_ERROR_MISALIGNED_ADDRESS on row 1.)
    __shared__ unsigned char smem_Ap_pq[2][DEV_M_TILE][K_STEP_T64 / 2 + 16];
    __shared__ unsigned char smem_As_pq[2][DEV_M_TILE][K_STEP_T64 / GROUP_SIZE];
    // B checkpoint layout is [K/2,N]; load it coalesced, then transpose the
    // 32-byte K run required by the native block-scaled MMA.
    __shared__ unsigned char smem_BpT_pq[2][K_STEP_T64 / 2][N_TILE_LG + BP_PAD];
    __shared__ unsigned char smem_Bp_pq[N_TILE_LG][K_STEP_T64 / 2 + 16];
    __shared__ unsigned char smem_Bs_pq[2][K_STEP_T64 / GROUP_SIZE][N_TILE_LG];
    __shared__ int smem_tok_pq[DEV_M_TILE];

    if (threadIdx.x < DEV_M_TILE) {
        const int local_row = threadIdx.x;
        if (sorted_token_ids && (cta_m_local + local_row) < (unsigned int)M_expert)
            smem_tok_pq[local_row] = sorted_token_ids[cta_m + local_row];
        else
            smem_tok_pq[local_row] = (int)(cta_m + local_row);
    }
    __syncthreads();

    float acc[16][4];
    #pragma unroll
    for (int i = 0; i < 16; i++) {
        acc[i][0] = 0.0f; acc[i][1] = 0.0f;
        acc[i][2] = 0.0f; acc[i][3] = 0.0f;
    }

    const unsigned int M_eff = (unsigned int)M_expert;
    const unsigned int num_groups = K / GROUP_SIZE;

    #define PQ4_ISSUE_LOADS(buf, kb) do { \
        { \
            /* 256 threads: two 16-byte copies for each of 128 A rows. */ \
            unsigned row = threadIdx.x >> 1; \
            unsigned col = (threadIdx.x & 1) << 4; \
            bool valid = (cta_m_local + row) < M_eff && ((kb) + col * 2 + 31 < K); \
            unsigned a_row = (unsigned)smem_tok_pq[row]; \
            moe_cp_async_pred_16(&smem_Ap_pq[(buf)][row][col], \
                &A_packed[(unsigned long long)a_row * (K / 2) + (kb) / 2 + col], valid); \
        } \
        if (threadIdx.x < 128) { \
            unsigned row = threadIdx.x; \
            bool valid = (cta_m_local + row) < M_eff; \
            unsigned a_row = (unsigned)smem_tok_pq[row]; \
            moe_cp_async_pred_4(&smem_As_pq[(buf)][row][0], \
                &A_scale[(unsigned long long)a_row * (K / GROUP_SIZE) + (kb) / GROUP_SIZE], valid); \
            /* Original B load schedule; upper four warps reuse this tile. */ \
            unsigned kp = threadIdx.x >> 3; \
            unsigned ns = (threadIdx.x & 7) << 4; \
            unsigned gns = cta_n + ns; \
            _Pragma("unroll") \
            for (int rnd = 0; rnd < 2; rnd++) { \
                unsigned kp_cur = rnd * 16 + kp; \
                unsigned gke = (kb) + (kp_cur << 1); \
                moe_cp_async_pred_16(&smem_BpT_pq[(buf)][kp_cur][ns], \
                    &B_expert[(unsigned long long)(gke >> 1) * N + gns], \
                    (gke + 1 < K) && (gns + 15 < N)); \
            } \
        } \
        if (threadIdx.x < 32) { \
            unsigned g = threadIdx.x >> 3; \
            unsigned ns = (threadIdx.x & 7) << 4; \
            unsigned sg = (kb) / GROUP_SIZE + g; \
            unsigned gns = cta_n + ns; \
            moe_cp_async_pred_16(&smem_Bs_pq[(buf)][g][ns], \
                &S_expert[(unsigned long long)sg * N + gns], \
                (gns + 15 < N) && (sg < num_groups)); \
        } \
    } while(0)

    #define PQ4_TRANSPOSE(buf) do { \
        if (threadIdx.x < 128) { \
        unsigned int my_n = threadIdx.x; \
        _Pragma("unroll") \
        for (int q = 0; q < (K_STEP_T64 / 2) / 4; q++) { \
            unsigned int w = (unsigned int)smem_BpT_pq[(buf)][q * 4 + 0][my_n] \
                | ((unsigned int)smem_BpT_pq[(buf)][q * 4 + 1][my_n] << 8) \
                | ((unsigned int)smem_BpT_pq[(buf)][q * 4 + 2][my_n] << 16) \
                | ((unsigned int)smem_BpT_pq[(buf)][q * 4 + 3][my_n] << 24); \
            *(unsigned int*)&smem_Bp_pq[my_n][q * 4] = w; \
        } \
        } \
    } while(0)

    #define PQ4_FRAG(P, ROW, KK) (*(const unsigned int*)&(P)[(ROW)][(KK) / 2])
    #define PQ4_COMPUTE_MMA(a_buf, b_buf) do { \
        unsigned int ra = warp_m_offset + group_id; \
        unsigned int a0 = PQ4_FRAG(smem_Ap_pq[(a_buf)], ra,     tid * 8); \
        unsigned int a1 = PQ4_FRAG(smem_Ap_pq[(a_buf)], ra + 8, tid * 8); \
        unsigned int a2 = PQ4_FRAG(smem_Ap_pq[(a_buf)], ra,     32 + tid * 8); \
        unsigned int a3 = PQ4_FRAG(smem_Ap_pq[(a_buf)], ra + 8, 32 + tid * 8); \
        unsigned int sfa_m = (lane_id & 1) * 8 + (lane_id >> 2); \
        unsigned int sfa = (unsigned int)smem_As_pq[(a_buf)][warp_m_offset + sfa_m][0] \
            | ((unsigned int)smem_As_pq[(a_buf)][warp_m_offset + sfa_m][1] << 8) \
            | ((unsigned int)smem_As_pq[(a_buf)][warp_m_offset + sfa_m][2] << 16) \
            | ((unsigned int)smem_As_pq[(a_buf)][warp_m_offset + sfa_m][3] << 24); \
        _Pragma("unroll") \
        for (int nt = 0; nt < 16; nt++) { \
            unsigned int nc = nt * 8 + group_id; \
            unsigned int b0 = PQ4_FRAG(smem_Bp_pq, nc, tid * 8); \
            unsigned int b1 = PQ4_FRAG(smem_Bp_pq, nc, 32 + tid * 8); \
            unsigned int sfn = nt * 8 + (lane_id >> 2); \
            unsigned int sfb = (unsigned int)smem_Bs_pq[(b_buf)][0][sfn] \
                | ((unsigned int)smem_Bs_pq[(b_buf)][1][sfn] << 8) \
                | ((unsigned int)smem_Bs_pq[(b_buf)][2][sfn] << 16) \
                | ((unsigned int)smem_Bs_pq[(b_buf)][3][sfn] << 24); \
            unsigned short bidA = 0, tidA_ = 0, bidB = 0, tidB_ = 0; \
            asm volatile( \
                "mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 " \
                "{%0,%1,%2,%3},{%4,%5,%6,%7},{%8,%9},{%10,%11,%12,%13}," \
                "{%14},{%15,%16},{%17},{%18,%19};" \
                :"=f"(acc[nt][0]),"=f"(acc[nt][1]),"=f"(acc[nt][2]),"=f"(acc[nt][3]) \
                :"r"(a0),"r"(a1),"r"(a2),"r"(a3),"r"(b0),"r"(b1), \
                 "f"(acc[nt][0]),"f"(acc[nt][1]),"f"(acc[nt][2]),"f"(acc[nt][3]), \
                 "r"(sfa),"h"(bidA),"h"(tidA_),"r"(sfb),"h"(bidB),"h"(tidB_)); \
        } \
    } while(0)

    PQ4_ISSUE_LOADS(0, 0);
    moe_cp_async_commit();
    moe_cp_async_wait_all();
    __syncthreads();
    PQ4_TRANSPOSE(0);
    __syncthreads();

    int cur = 0;
    for (unsigned int k_base = K_STEP_T64; k_base < K; k_base += K_STEP_T64) {
        int nxt = 1 - cur;
        PQ4_ISSUE_LOADS(nxt, k_base);
        moe_cp_async_commit();
        PQ4_COMPUTE_MMA(cur, cur);
        moe_cp_async_wait_all();
        __syncthreads();
        PQ4_TRANSPOSE(nxt);
        __syncthreads();
        cur = nxt;
    }
    PQ4_COMPUTE_MMA(cur, cur);

    #undef PQ4_ISSUE_LOADS
    #undef PQ4_TRANSPOSE
    #undef PQ4_FRAG
    #undef PQ4_COMPUTE_MMA

    #pragma unroll
    for (int nt = 0; nt < 16; nt++) {
        unsigned int c0 = cta_n + nt * 8 + tid * 2;
        unsigned int c1 = c0 + 1;
        unsigned int r0 = cta_m + warp_m_offset + group_id;
        unsigned int r1 = r0 + 8;
        bool r0v = (int)(warp_m_offset + group_id + cta_m_local) < M_expert;
        bool r1v = (int)(warp_m_offset + group_id + 8 + cta_m_local) < M_expert;
        if (r0v && c0 < N) C[r0 * N + c0] = __float2bfloat16(acc[nt][0] * scale2);
        if (r0v && c1 < N) C[r0 * N + c1] = __float2bfloat16(acc[nt][1] * scale2);
        if (r1v && c0 < N) C[r1 * N + c0] = __float2bfloat16(acc[nt][2] * scale2);
        if (r1v && c1 < N) C[r1 * N + c1] = __float2bfloat16(acc[nt][3] * scale2);
    }
}

extern "C" __global__ void atlas_dev_moe_m128(
    const unsigned char* a, const unsigned char* as,
    const unsigned long long* bp, const unsigned long long* bs,
    const float* scales, __nv_bfloat16* out, const int* offsets,
    const int* ids, unsigned experts, unsigned n, unsigned k) {
    if (blockDim.x != 256 || blockDim.y != 1 || blockDim.z != 1
        || k % 64 != 0 || n % 128 != 0) return;
    atlas_dev_moe_m128_impl<true>(a, as, bp, bs, scales, out, offsets,
        ids, experts, n, k, blockIdx.z, blockIdx.y, blockIdx.x);
}
