# SPDX-License-Identifier: AGPL-3.0-only
"""Pinned M64 body: double M/warps, reuse original B stage and MMA order."""
from pathlib import Path
import hashlib

HERE = Path(__file__).resolve().parent
SOURCE = HERE.parents[2] / 'kernels/gb10/deepseek-v4-flash/nvfp4/moe_w4a16_grouped_gemm.cu'
SHA = 'bad2afc59183a4b46fd094864ef88ae428517a23dee0d00f1d9e87de7503b33b'
assert hashlib.sha256(SOURCE.read_bytes()).hexdigest() == SHA, 'source changed: review first'
src = SOURCE.read_text()
begin = src.index('template<bool PQ_VEC_SCALES>\n__device__ __forceinline__ void moe_w4a4_grouped_gemm_prequant_t_k64_impl(')
end = src.index('\n#define PQ4_PREQUANT_ARGS', begin)
original = src[begin:end]
body = original.replace('moe_w4a4_grouped_gemm_prequant_t_k64_impl', 'atlas_dev_moe_m128_impl')
body = body.replace('M_TILE', 'DEV_M_TILE')
body = body.replace(') {\n    const unsigned int expert_id', ') {\n    static_assert(PQ_VEC_SCALES, "vector scales only");\n    constexpr unsigned DEV_M_TILE = 128;\n    const unsigned int expert_id', 1)
a = body.index('    #define PQ4_ISSUE_LOADS')
b = body.index('    #define PQ4_TRANSPOSE', a)
body = body[:a] + r'''    #define PQ4_ISSUE_LOADS(buf, kb) do { \
        { \
            /* 256 threads: two 16-byte copies for each of 128 A rows. */ \
            unsigned row = threadIdx.x >> 1; \
            unsigned col = (threadIdx.x & 1) << 4; \
            bool valid = (cta_m_local + row) < M_eff && ((kb) + col * 2 + 31 < K); \
            unsigned a_row = (unsigned)smem_tok_pq[row]; \
            moe_cp_async_pred_16(&smem_Ap_pq[(buf)][row][col], \
                &A_packed[(unsigned long long)a_row * (K / 2) + (kb) / 2 + col], valid); \
        } \
        if (threadIdx.x < 128) { \
            unsigned row = threadIdx.x; \
            bool valid = (cta_m_local + row) < M_eff; \
            unsigned a_row = (unsigned)smem_tok_pq[row]; \
            moe_cp_async_pred_4(&smem_As_pq[(buf)][row][0], \
                &A_scale[(unsigned long long)a_row * (K / GROUP_SIZE) + (kb) / GROUP_SIZE], valid); \
            /* Original B load schedule; upper four warps reuse this tile. */ \
            unsigned kp = threadIdx.x >> 3; \
            unsigned ns = (threadIdx.x & 7) << 4; \
            unsigned gns = cta_n + ns; \
            _Pragma("unroll") \
            for (int rnd = 0; rnd < 2; rnd++) { \
                unsigned kp_cur = rnd * 16 + kp; \
                unsigned gke = (kb) + (kp_cur << 1); \
                moe_cp_async_pred_16(&smem_BpT_pq[(buf)][kp_cur][ns], \
                    &B_expert[(unsigned long long)(gke >> 1) * N + gns], \
                    (gke + 1 < K) && (gns + 15 < N)); \
            } \
        } \
        if (threadIdx.x < 32) { \
            unsigned g = threadIdx.x >> 3; \
            unsigned ns = (threadIdx.x & 7) << 4; \
            unsigned sg = (kb) / GROUP_SIZE + g; \
            unsigned gns = cta_n + ns; \
            moe_cp_async_pred_16(&smem_Bs_pq[(buf)][g][ns], \
                &S_expert[(unsigned long long)sg * N + gns], \
                (gns + 15 < N) && (sg < num_groups)); \
        } \
    } while(0)

''' + body[b:]
body = body.replace('    #define PQ4_TRANSPOSE(buf) do { \\\n', '    #define PQ4_TRANSPOSE(buf) do { \\\n        if (threadIdx.x < 128) { \\\n', 1)
needle = '    #define PQ4_FRAG'
pos = body.index(needle)
prefix = body[:pos]
last = prefix.rindex('    } while(0)')
body = prefix[:last] + '        } \\\n' + prefix[last:] + body[pos:]
# These exact regions contain all accumulator operations and pipeline ordering.
for start, stop in [('    #define PQ4_FRAG', '    #undef PQ4_ISSUE_LOADS'), ('    #pragma unroll\n    for (int nt = 0;', '\n}\n')]:
 old = original[original.index(start):original.index(stop, original.index(start))]
 new = body[body.index(start):body.index(stop, body.index(start))]
 assert old == new, 'MMA, K order, or output conversion changed'
body += '''
extern "C" __global__ void atlas_dev_moe_m128(
    const unsigned char* a, const unsigned char* as,
    const unsigned long long* bp, const unsigned long long* bs,
    const float* scales, __nv_bfloat16* out, const int* offsets,
    const int* ids, unsigned experts, unsigned n, unsigned k) {
    if (blockDim.x != 256 || blockDim.y != 1 || blockDim.z != 1
        || k % 64 != 0 || n % 128 != 0) return;
    atlas_dev_moe_m128_impl<true>(a, as, bp, bs, scales, out, offsets,
        ids, experts, n, k, blockIdx.z, blockIdx.y, blockIdx.x);
}
'''
(HERE / 'candidate.cuh').write_text('// SPDX-License-Identifier: AGPL-3.0-only\n// Generated by generate.py; production source SHA256: ' + SHA + '\n' + body)
print('PASS generated: original MMA, ordered K64 pipeline, output conversion unchanged')
