# SPDX-License-Identifier: AGPL-3.0-only
"""Extract the pinned production body and widen staging, not its MMA arithmetic."""
from pathlib import Path
import hashlib

HERE = Path(__file__).resolve().parent
SOURCE = HERE.parents[2] / "kernels/gb10/deepseek-v4-flash/nvfp4/moe_w4a16_grouped_gemm.cu"
SHA = "bad2afc59183a4b46fd094864ef88ae428517a23dee0d00f1d9e87de7503b33b"
assert hashlib.sha256(SOURCE.read_bytes()).hexdigest() == SHA, "upstream body changed; review before regeneration"
source = SOURCE.read_text()
begin = source.index("template<bool PQ_VEC_SCALES>\n__device__ __forceinline__ void moe_w4a4_grouped_gemm_prequant_t_k64_impl(")
end = source.index("\n#define PQ4_PREQUANT_ARGS", begin)
body = source[begin:end]
body = body.replace("moe_w4a4_grouped_gemm_prequant_t_k64_impl", "atlas_dev_moe_k128_impl")
# Each ping-pong slot now owns two consecutive K64 segments. The transpose
# outputs are also disjoint, so both segments can be transposed before a barrier.
for name in ["Ap", "As", "BpT", "Bs"]:
    body = body.replace(f"smem_{name}_pq[2]", f"smem_{name}_pq[2][2]")
    body = body.replace(f"smem_{name}_pq[(buf)]", f"smem_{name}_pq[(buf)][(half)]")
    body = body.replace(f"smem_{name}_pq[(a_buf)]", f"smem_{name}_pq[(a_buf)][(half)]")
    body = body.replace(f"smem_{name}_pq[(b_buf)]", f"smem_{name}_pq[(b_buf)][(half)]")
body = body.replace("smem_Bp_pq[N_TILE_LG]", "smem_Bp_pq[2][N_TILE_LG]")
body = body.replace("smem_Bp_pq[my_n]", "smem_Bp_pq[(half)][my_n]")
body = body.replace("PQ4_FRAG(smem_Bp_pq,", "PQ4_FRAG(smem_Bp_pq[(half)],")
body = body.replace("PQ4_ISSUE_LOADS(buf, kb)", "PQ4_ISSUE_LOADS(buf, half, kb)")
body = body.replace("PQ4_TRANSPOSE(buf)", "PQ4_TRANSPOSE(buf, half)")
body = body.replace("PQ4_COMPUTE_MMA(a_buf, b_buf)", "PQ4_COMPUTE_MMA(a_buf, b_buf, half)")
a = body.index("    PQ4_ISSUE_LOADS(0, 0);")
b = body.index("    #undef PQ4_ISSUE_LOADS", a)
body = body[:a] + """    PQ4_ISSUE_LOADS(0, 0, 0);
    PQ4_ISSUE_LOADS(0, 1, 64);
    moe_cp_async_commit();
    moe_cp_async_wait_all();
    __syncthreads();
    PQ4_TRANSPOSE(0, 0);
    PQ4_TRANSPOSE(0, 1);
    __syncthreads();
    int cur = 0;
    for (unsigned int k_base = 128; k_base < K; k_base += 128) {
        const int nxt = 1 - cur;
        PQ4_ISSUE_LOADS(nxt, 0, k_base);
        PQ4_ISSUE_LOADS(nxt, 1, k_base + 64);
        moe_cp_async_commit();
        // Each accumulator executes the same ordered sequence of K64 MMAs.
        PQ4_COMPUTE_MMA(cur, cur, 0);
        PQ4_COMPUTE_MMA(cur, cur, 1);
        moe_cp_async_wait_all();
        __syncthreads();
        PQ4_TRANSPOSE(nxt, 0);
        PQ4_TRANSPOSE(nxt, 1);
        __syncthreads();
        cur = nxt;
    }
    PQ4_COMPUTE_MMA(cur, cur, 0);
    PQ4_COMPUTE_MMA(cur, cur, 1);

""" + body[b:]
body += """
extern "C" __global__ void atlas_dev_moe_k128(
    const unsigned char* a, const unsigned char* as,
    const unsigned long long* bp, const unsigned long long* bs,
    const float* scales, __nv_bfloat16* out, const int* offsets,
    const int* ids, unsigned experts, unsigned n, unsigned k) {
    if (k % 128 != 0) return;
    atlas_dev_moe_k128_impl<true>(a, as, bp, bs, scales, out, offsets,
        ids, experts, n, k, blockIdx.z, blockIdx.y, blockIdx.x);
}
"""
header = "// SPDX-License-Identifier: AGPL-3.0-only\n// Generated by generate.py; do not edit.\n// Production source SHA256: " + SHA + "\n"
(HERE / "candidate.cuh").write_text(header + body)
assert body.count("PQ4_COMPUTE_MMA(cur, cur, 0)") == 2
assert body.count("PQ4_COMPUTE_MMA(cur, cur, 1)") == 2
print("Generated candidate.cuh: K64 MMA body retained; K128 two-segment staging")
