#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-only
"""Derive a reduced MTP draft vocabulary for qwen4_exp (Qwen3.8-Flash-Next).

The list feeds `ATLAS_QWEN4EXP_DRAFT_VOCAB=<file>`
(`crates/spark-model/src/layers/qwen4exp_draft_head.rs`): the drafter's
argmax runs over these rows of the shared LM head only. Drafts are always
re-verified by the full head, so the list moves acceptance, never output.

Selection, in order, until `--size` ids:
  1. every id below `--keep-below` (BPE ranks frequent merges low);
  2. every added/special token of the tokenizer (`<think>`, `</think>`,
     `<tool_call>`, ... — a prefix rule drops these, and each one the
     drafter cannot propose is a guaranteed rejection);
  3. every single-character token (the byte-level alphabet);
  4. the most frequent ids when tokenizing `--corpus` (files or directories,
     read as UTF-8 text). The best corpus is the served model's own outputs
     on the target workload; a public-domain/permissively licensed text set
     (e.g. the local CPython stdlib, PSF license) is a reasonable default.

The output is one id per line, ascending, after a `#` header recording the
inputs, so a list is reproducible from its header. Prints the SHA-256.

Example:
  python3 scripts/dev/qwen4exp_draft_vocab.py \\
      --tokenizer /models/Qwen3.8-Flash-Next/tokenizer.json \\
      --corpus "$(python3 -c 'import sysconfig;print(sysconfig.get_paths()["stdlib"])')" \\
      --corpus outputs/ --size 80000 --keep-below 65536 --out draft_vocab.txt

Needs `tokenizers` (pip install tokenizers).
"""

import argparse
import collections
import hashlib
import json
import os
import sys

TEXT_EXT = {".py", ".txt", ".md", ".rst", ".json", ".jsonl", ".html", ".c", ".h", ".rs", ".js", ".ts"}


def corpus_files(paths):
    for p in paths:
        if os.path.isdir(p):
            for root, _, names in os.walk(p):
                for n in sorted(names):
                    if os.path.splitext(n)[1].lower() in TEXT_EXT:
                        yield os.path.join(root, n)
        else:
            yield p


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--tokenizer", required=True, help="tokenizer.json (or a model dir holding one)")
    ap.add_argument("--corpus", action="append", default=[], help="text file or directory (repeatable)")
    ap.add_argument("--size", type=int, required=True, help="ids in the list")
    ap.add_argument("--keep-below", type=int, default=0, help="always keep ids below this")
    ap.add_argument("--vocab", type=int, default=248320, help="model vocab_size (ids must be below)")
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    from tokenizers import Tokenizer

    tok_path = args.tokenizer
    if os.path.isdir(tok_path):
        tok_path = os.path.join(tok_path, "tokenizer.json")
    tok = Tokenizer.from_file(tok_path)
    with open(tok_path, encoding="utf-8") as f:
        added = sorted({t["id"] for t in json.load(f).get("added_tokens", [])})

    keep = set(range(min(args.keep_below, args.vocab)))
    keep.update(i for i in added if i < args.vocab)
    for piece, i in tok.get_vocab(with_added_tokens=False).items():
        if len(piece) == 1 and i < args.vocab:
            keep.add(i)
    pinned = len(keep)
    if pinned > args.size:
        sys.exit(f"--size {args.size} is below the {pinned} pinned ids")

    counts = collections.Counter()
    files = list(corpus_files(args.corpus))
    for path in files:
        try:
            with open(path, encoding="utf-8") as f:
                text = f.read()
        except (UnicodeDecodeError, OSError):
            continue
        # Chunk long files: the tokenizer is fine with them, memory is not.
        for start in range(0, len(text), 1 << 20):
            counts.update(tok.encode(text[start : start + (1 << 20)], add_special_tokens=False).ids)
    for i, _ in counts.most_common():
        if len(keep) >= args.size:
            break
        if i < args.vocab:
            keep.add(i)
    ids = sorted(keep)

    header = [
        "# qwen4_exp MTP draft vocabulary (ATLAS_QWEN4EXP_DRAFT_VOCAB)",
        "# generated by scripts/dev/qwen4exp_draft_vocab.py",
        f"# tokenizer: {os.path.abspath(tok_path)}",
        f"# size={args.size} keep_below={args.keep_below} vocab={args.vocab}",
        f"# pinned (prefix + added + single-char): {pinned}; corpus files: {len(files)}; "
        f"distinct corpus ids: {len(counts)}",
    ] + [f"# corpus: {os.path.abspath(c)}" for c in args.corpus]
    body = "\n".join(map(str, ids)) + "\n"
    with open(args.out, "w", encoding="utf-8") as f:
        f.write("\n".join(header) + "\n" + body)
    sha = hashlib.sha256(body.encode()).hexdigest()
    print(f"{args.out}: {len(ids)} ids (pinned {pinned}); sha256(ids) {sha}")


if __name__ == "__main__":
    main()
